# CMake generated Testfile for 
# Source directory: /home/redd/dolphin-master/Source/UnitTests/Common
# Build directory: /home/redd/libretro-super/recipes/apple/Source/UnitTests/Common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BitFieldTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/BitFieldTest")
set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BitSetTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/BitSetTest")
set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BitUtilsTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/BitUtilsTest")
set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BlockingLoopTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/BlockingLoopTest")
set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BusyLoopTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/BusyLoopTest")
set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(CommonFuncsTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/CommonFuncsTest")
set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(CryptoEcTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/CryptoEcTest")
set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(EventTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/EventTest")
set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FixedSizeQueueTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/FixedSizeQueueTest")
set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FlagTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/FlagTest")
set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FloatUtilsTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/FloatUtilsTest")
set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(MathUtilTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/MathUtilTest")
set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(NandPathsTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/NandPathsTest")
set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(SPSCQueueTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/SPSCQueueTest")
set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(StringUtilTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/StringUtilTest")
set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(SwapTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/SwapTest")
set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(x64EmitterTest "/home/redd/libretro-super/recipes/apple/Binaries/Tests/x64EmitterTest")
set_tests_properties(x64EmitterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/redd/dolphin-master/Source/UnitTests/CMakeLists.txt;21;add_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;19;add_dolphin_test;/home/redd/dolphin-master/Source/UnitTests/Common/CMakeLists.txt;0;")
